# Whether all players should have the speedometer enabled by default
enabled-by-default: false
# Whether players should be allowed to toggle the speedometer
allow-toggle: true
# The more players the server has, the higher this should be
update-rate-in-ticks: 20
# Whether the speed should be shown in the players action-bar
show-in-actionbar: true
# It is assumed that PlaceholderAPI is not installed. PlaceholderAPI is not supported in any messages.
messages:
  enabled-speedometer: "&eSpeedometer is now &aenabled&e!"
  disabled-speedometer: "&eSpeedometer is now &cdisabled&e!"
  toggling-not-allowed: "&cToggling the speedometer is not allowed."
  actionbar-format: "&a%speed%"
